[package]
name = "nebula"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.11"
wgpu = "25.0.2"
cosmic-text = "0.14.2"
portable-pty = "0.9.0"
anyhow = "1.0.98"
pollster = "0.4.0"
bytemuck = "1.23.1"
futures = "0.3.31"
tokio = { version = "1.45.1", features = ["full"] }